name: E2E Testing
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies...
        run: npm -i

      - name: Run tests
        run: npx cypress run
